config/routes.rb
Rails.application.routes.draw do

  resources :doors do
    resources :magnets, defaults: {format: :json}
  end

  root to: 'doors#index'
end

app/models/door.rb
class Door < ActiveRecord::Base
  before_create :generate_hex
  has_many :magnets

  accepts_nested_attributes_for :magnets

  validates :name, presence: true
  attr_accessor :wordlist

  delegate :subscribers, to: :websocket_channel

  def to_param
    self.hex
  end

  def websocket_channel
    WebsocketRails["door-#{self.hex}"]
  end

  def trigger event, data
    websocket_channel.trigger(event, data)
  end

  def update_subscribers
    # TODO allow removal of subscribers
    data = {hex: self.hex, subscribers: self.subscribers.length+1}
    WebsocketRails['doors'].trigger('subscriber-joined', data)
  end

  private
  def generate_hex
    self.hex = SecureRandom.hex
  end

  DEFAULT_WORDS = %w(man the cat dog chicken ate looked at the a car metal 
    ran swam fly plane moon left woman wife girl boy computer an of look
    take wants car phone computer sing hear call)
end

app/models/magnet.rb
class Magnet < ActiveRecord::Base
  belongs_to :door
  before_create :set_coordinates

  XRANGE = (0..1240)
  YRANGE = (0..700)

  def position_style
    "left: #{x}px; top: #{y}px;"
  end

  def trigger_update
    door.trigger('update', self)
  end

private
  def set_coordinates
    self.x = XRANGE.to_a.sample
    self.y = YRANGE.to_a.sample
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

protected

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end  
end

app/controllers/doors_controller.rb
class DoorsController < ApplicationController
  before_action :set_door, only: [:show, :edit, :update, :destroy]

  respond_to :json, :html

  # GET /doors
  # GET /doors.json
  def index
    @doors = Door.where(private: false)
    respond_with @doors
  end

  # GET /doors/1
  # GET /doors/1.json
  def show
    @door.update_subscribers
  end

  # GET /doors/new
  def new
    @door = Door.new(wordlist: Door::DEFAULT_WORDS)
  end

  # GET /doors/1/edit
  def edit
  end

  # POST /doors
  # POST /doors.json
  def create
    # TODO: Clean up, possibly on Angular side by using magnets_attributes
    edited_params = door_params
    words = edited_params.delete(:words)
    magnets_attributes = words.map{|w| {word: w}}
    @door = Door.new(edited_params.merge(magnets_attributes: magnets_attributes))

    respond_to do |format|
      if @door.save
        format.html { redirect_to @door, notice: 'Door was successfully created.' }
        format.json { render :show, status: :created, location: @door }
      else
        format.json { render json: @door.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doors/1
  # PATCH/PUT /doors/1.json
  def update
    respond_to do |format|
      if @door.update(door_params)
        format.html { redirect_to @door, notice: 'Door was successfully updated.' }
        format.json { render :show, status: :ok, location: @door }
      else
        format.html { render :edit }
        format.json { render json: @door.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doors/1
  # DELETE /doors/1.json
  def destroy
    @door.destroy
    respond_to do |format|
      format.html { redirect_to doors_url, notice: 'Door was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_door
      @door = Door.find_by!(hex: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def door_params
      params.require(:door).permit(:name, words: [])
    end
end

app/controllers/magnets_controller.rb
class MagnetsController < ApplicationController
  before_action :set_magnet, only: [:show, :edit, :update, :destroy]
  before_action :set_door

  # GET /magnets
  # GET /magnets.json
  def index
    @magnets = @door.magnets
  end

  # GET /magnets/1
  # GET /magnets/1.json
  def show
  end

  # GET /magnets/new
  def new
    @magnet = Magnet.new
  end

  # GET /magnets/1/edit
  def edit
  end

  # POST /magnets
  # POST /magnets.json
  def create
    @magnet = Magnet.new(magnet_params)

    respond_to do |format|
      if @magnet.save
        format.html { redirect_to @magnet, notice: 'Magnet was successfully created.' }
        format.json { render :show, status: :created, location: @magnet }
      else
        format.html { render :new }
        format.json { render json: @magnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magnets/1
  # PATCH/PUT /magnets/1.json
  def update
    respond_to do |format|
      if @magnet.update(magnet_params)
        @magnet.trigger_update
        format.html { redirect_to door_magnet_path(@door, @magnet), notice: 'Magnet was successfully updated.' }
        format.json { render :show, status: :ok, location: door_magnet_url(@door, @magnet) }
      else
        format.html { render :edit }
        format.json { render json: @magnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magnets/1
  # DELETE /magnets/1.json
  def destroy
    @magnet.destroy
    respond_to do |format|
      format.html { redirect_to magnets_url, notice: 'Magnet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magnet
      @magnet = Magnet.find(params[:id])
    end

    def set_door
      #@door = Door.find(params[:door_id])
      @door = Door.find_by!(hex: params[:door_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magnet_params
      params.require(:magnet).permit(:x, :y, :word, :locked_until, :locked_by, :fridge_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doors_helper.rb
module DoorsHelper
end

app/helpers/magnets_helper.rb
module MagnetsHelper
end

app/views/doors/_form.html.slim
form ng-submit="createDoor()" 
  .field
    = text_field_tag :name, '', placeholder: 'name', 'ng-model' => 'door.name'

  .field
    .hint Type and press enter to add words. Click to remove.
    .wordlist-wrapper focus-input=".new-word"
      span.word ng-repeat="word in door.words track by $index" ng-click="remove(word);"
        | {{word}}
      = text_field_tag 'add_word', '', class: 'new-word', placeholder: 'add word', 'ng-model' => 'newWord', 'ui-keydown' => "{'enter': 'createWord($event)', 'backspace':'removeLastWord($event)'}"

  .field.actions
    = submit_tag

app/views/doors/edit.html.erb
<h1>Editing door</h1>

<%= render 'form' %>

<%= link_to 'Show', @door %> |
<%= link_to 'Back', doors_path %>

app/views/doors/index.html.slim
- content_for :title do
  | Public Doors
.centered
  #doors ng-controller="DoorIndexController"
    .door ng-repeat="door in doors"
      = link_to "{{door.url | removeExtension}}" do
        span 
          | {{door.name}}
        span.subscribers
          | {{door.subscribers}}

app/views/doors/new.html.slim
.centered
  h1 New Door
  div ng-controller="DoorFormController" ng-init="init(['#{@door.wordlist.join('\',\'')}'])"
    = render 'form'

app/views/doors/show.html.slim
- content_for(:title) do
  = @door.name

#door ng-controller="DoorController" ng-init="init('#{@door.hex}')"
    div.magnet id="{{magnet.id + '-magnet'}}" ng-repeat="magnet in magnets" ng-draggable="{stop:updateMagnet}" ng-style="{'left': magnet.x, 'top': magnet.y}" ng-drag-success="" class="ng-cloak"
      | {{magnet.word}}

app/views/layouts/_header.html.slim
header
  .menu
    = link_to 'all doors', doors_path
    = link_to 'create', new_door_path, class: 'button'
  #logo
  = yield :title

app/views/layouts/application.html.slim
doctype html
html ng-app="fridgeApp"
head
  title Fridge
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'application'
  / TODO: Use Restangular?
  / 'http://cdnjs.cloudflare.com/ajax/libs/restangular/1.3.1/restangular.min.js'
  = csrf_meta_tags
body
  = render 'layouts/header'
  = yield

app/views/magnets/_form.html.erb
<%= form_for(@magnet) do |f| %>
  <% if @magnet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magnet.errors.count, "error") %> prohibited this magnet from being saved:</h2>

      <ul>
      <% @magnet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x %><br>
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br>
    <%= f.number_field :y %>
  </div>
  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :locked_until %><br>
    <%= f.datetime_select :locked_until %>
  </div>
  <div class="field">
    <%= f.label :locked_by %><br>
    <%= f.number_field :locked_by %>
  </div>
  <div class="field">
    <%= f.label :fridge_id %><br>
    <%= f.number_field :fridge_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/magnets/edit.html.erb
<h1>Editing magnet</h1>

<%= render 'form' %>

<%= link_to 'Show', @magnet %> |
<%= link_to 'Back', magnets_path %>

app/views/magnets/index.html.erb
<h1>Listing magnets</h1>

<table>
  <thead>
    <tr>
      <th>X</th>
      <th>Y</th>
      <th>Word</th>
      <th>Locked until</th>
      <th>Locked by</th>
      <th>Fridge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magnets.each do |magnet| %>
      <tr>
        <td><%= magnet.x %></td>
        <td><%= magnet.y %></td>
        <td><%= magnet.word %></td>
        <td><%= magnet.locked_until %></td>
        <td><%= magnet.locked_by %></td>
        <td><%= magnet.fridge_id %></td>
        <td><%= link_to 'Show', magnet %></td>
        <td><%= link_to 'Edit', edit_magnet_path(magnet) %></td>
        <td><%= link_to 'Destroy', magnet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magnet', new_magnet_path %>

app/views/magnets/new.html.erb
<h1>New magnet</h1>

<%= render 'form' %>

<%= link_to 'Back', magnets_path %>

app/views/magnets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>X:</strong>
  <%= @magnet.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @magnet.y %>
</p>

<p>
  <strong>Word:</strong>
  <%= @magnet.word %>
</p>

<p>
  <strong>Locked until:</strong>
  <%= @magnet.locked_until %>
</p>

<p>
  <strong>Locked by:</strong>
  <%= @magnet.locked_by %>
</p>

<p>
  <strong>Fridge:</strong>
  <%= @magnet.fridge_id %>
</p>

<%= link_to 'Edit', edit_magnet_path(@magnet) %> |
<%= link_to 'Back', magnets_path %>